create_clock -period 10.000 -name BANK35_L12P_MRCC_100M [get_ports BANK35_L12P_MRCC_100M]
create_clock -period 10.000 -name BANK34_L13P_MRCC_100M [get_ports BANK34_L13P_MRCC_100M]

set_property IOSTANDARD LVCMOS33 [get_ports Board_ID3]
set_property IOSTANDARD LVCMOS33 [get_ports Board_ID2]
set_property IOSTANDARD LVCMOS33 [get_ports Board_ID1]
set_property IOSTANDARD LVCMOS33 [get_ports Board_ID0]
set_property IOSTANDARD LVCMOS33 [get_ports PUDC_B]
set_property IOSTANDARD LVCMOS33 [get_ports BANK35_L12P_MRCC_100M]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L13P_MRCC_100M]
set_property IOSTANDARD LVCMOS33 [get_ports P_GOOD]
set_property IOSTANDARD LVCMOS33 [get_ports CLOCK_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports BANK35_L6P_LED_N]
set_property IOSTANDARD LVCMOS33 [get_ports BANK35_L7P_LED_N]
set_property IOSTANDARD LVCMOS33 [get_ports BANK35_L8P_LED_N]
set_property IOSTANDARD LVCMOS33 [get_ports BANK35_L9P_LED_N]

set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L1P_PLUG1]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L1N_RST1]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L2P_TXD1]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L2N_RXD1]

set_property IOSTANDARD LVCMOS33 [get_ports BANK34_0_PLUG2]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L3N_RST2]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L4P_TXD2]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L4N_RXD2]

set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L5P_PLUG3]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L5N_RST3]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L6P_TXD3]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L6N_RXD3]

set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L7P_PLUG4]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L7N_RST4]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L8P_TXD4]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L8N_RXD4]

set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L9P_PLUG5]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L9N_RST5]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L10P_TXD5]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L10N_RXD5]

set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L11P_PLUG6]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L11N_RST6]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L12P_TXD6]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L12N_RXD6]

set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L15P_PLUG7]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L15N_RST7]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L16P_TXD7]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L16N_RXD7]

set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L17P_PLUG8]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L17N_RST8]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L18P_TXD8]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L18N_RXD8]

set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L19P_PLUG9]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L19N_RST9]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L20P_TXD9]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L20N_RXD9]

set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L22P_SCL1]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L22N_SDA1]

set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L23P_SCL2]
set_property IOSTANDARD LVCMOS33 [get_ports BANK34_L23N_SDA2]

set_property IOSTANDARD LVCMOS33 [get_ports BANK35_L14P_FAN_PWM]
set_property IOSTANDARD LVCMOS33 [get_ports BANK35_L15P_FAN_SPEED1]
set_property IOSTANDARD LVCMOS33 [get_ports BANK35_L15N_FAN_SPEED2]
set_property IOSTANDARD LVCMOS33 [get_ports BANK35_L16P_FAN_SPEED3]
set_property IOSTANDARD LVCMOS33 [get_ports BANK35_L16N_FAN_SPEED4]
set_property IOSTANDARD LVCMOS33 [get_ports BANK35_L17P_FAN_SPEED5]
set_property IOSTANDARD LVCMOS33 [get_ports BANK35_L17N_FAN_SPEED6]

set_property PACKAGE_PIN L14 [get_ports Board_ID3]
set_property PACKAGE_PIN L15 [get_ports Board_ID2]
set_property PACKAGE_PIN M14 [get_ports Board_ID1]
set_property PACKAGE_PIN M15 [get_ports Board_ID0]
set_property PACKAGE_PIN U13 [get_ports PUDC_B]
set_property PACKAGE_PIN K17 [get_ports BANK35_L12P_MRCC_100M]
set_property PACKAGE_PIN N18 [get_ports BANK34_L13P_MRCC_100M]
set_property PACKAGE_PIN C7  [get_ports P_GOOD]
set_property PACKAGE_PIN K18 [get_ports CLOCK_OUT]
set_property PACKAGE_PIN F16 [get_ports BANK35_L6P_LED_N]
set_property PACKAGE_PIN M19 [get_ports BANK35_L7P_LED_N]
set_property PACKAGE_PIN M17 [get_ports BANK35_L8P_LED_N]
set_property PACKAGE_PIN L19 [get_ports BANK35_L9P_LED_N]

set_property PACKAGE_PIN T11 [get_ports BANK34_L1P_PLUG1]
set_property PACKAGE_PIN T10 [get_ports BANK34_L1N_RST1]
set_property PACKAGE_PIN T12 [get_ports BANK34_L2P_TXD1]
set_property PACKAGE_PIN U12 [get_ports BANK34_L2N_RXD1]

set_property PACKAGE_PIN R19 [get_ports BANK34_0_PLUG2]
set_property PACKAGE_PIN V13 [get_ports BANK34_L3N_RST2]
set_property PACKAGE_PIN V12 [get_ports BANK34_L4P_TXD2]
set_property PACKAGE_PIN W13 [get_ports BANK34_L4N_RXD2]

set_property PACKAGE_PIN T14 [get_ports BANK34_L5P_PLUG3]
set_property PACKAGE_PIN T15 [get_ports BANK34_L5N_RST3]
set_property PACKAGE_PIN P14 [get_ports BANK34_L6P_TXD3]
set_property PACKAGE_PIN R14 [get_ports BANK34_L6N_RXD3]

set_property PACKAGE_PIN Y16 [get_ports BANK34_L7P_PLUG4]
set_property PACKAGE_PIN Y17 [get_ports BANK34_L7N_RST4]
set_property PACKAGE_PIN W14 [get_ports BANK34_L8P_TXD4]
set_property PACKAGE_PIN Y14 [get_ports BANK34_L8N_RXD4]

set_property PACKAGE_PIN T16 [get_ports BANK34_L9P_PLUG5]
set_property PACKAGE_PIN U17 [get_ports BANK34_L9N_RST5]
set_property PACKAGE_PIN V15 [get_ports BANK34_L10P_TXD5]
set_property PACKAGE_PIN W15 [get_ports BANK34_L10N_RXD5]

set_property PACKAGE_PIN U14 [get_ports BANK34_L11P_PLUG6]
set_property PACKAGE_PIN U15 [get_ports BANK34_L11N_RST6]
set_property PACKAGE_PIN U18 [get_ports BANK34_L12P_TXD6]
set_property PACKAGE_PIN U19 [get_ports BANK34_L12N_RXD6]

set_property PACKAGE_PIN T20 [get_ports BANK34_L15P_PLUG7]
set_property PACKAGE_PIN U20 [get_ports BANK34_L15N_RST7]
set_property PACKAGE_PIN V20 [get_ports BANK34_L16P_TXD7]
set_property PACKAGE_PIN W20 [get_ports BANK34_L16N_RXD7]

set_property PACKAGE_PIN Y18 [get_ports BANK34_L17P_PLUG8]
set_property PACKAGE_PIN Y19 [get_ports BANK34_L17N_RST8]
set_property PACKAGE_PIN V16 [get_ports BANK34_L18P_TXD8]
set_property PACKAGE_PIN W16 [get_ports BANK34_L18N_RXD8]

set_property PACKAGE_PIN R16 [get_ports BANK34_L19P_PLUG9]
set_property PACKAGE_PIN R17 [get_ports BANK34_L19N_RST9]
set_property PACKAGE_PIN T17 [get_ports BANK34_L20P_TXD9]
set_property PACKAGE_PIN R18 [get_ports BANK34_L20N_RXD9]

set_property PACKAGE_PIN W18 [get_ports BANK34_L22P_SCL1]
set_property PACKAGE_PIN W19 [get_ports BANK34_L22N_SDA1]

set_property PACKAGE_PIN N17 [get_ports BANK34_L23P_SCL2]
set_property PACKAGE_PIN P18 [get_ports BANK34_L23N_SDA2]

set_property PACKAGE_PIN J18 [get_ports BANK35_L14P_FAN_PWM]
set_property PACKAGE_PIN F19 [get_ports BANK35_L15P_FAN_SPEED1]
set_property PACKAGE_PIN F20 [get_ports BANK35_L15N_FAN_SPEED2]
set_property PACKAGE_PIN G17 [get_ports BANK35_L16P_FAN_SPEED3]
set_property PACKAGE_PIN G18 [get_ports BANK35_L16N_FAN_SPEED4]
set_property PACKAGE_PIN J20 [get_ports BANK35_L17P_FAN_SPEED5]
set_property PACKAGE_PIN H20 [get_ports BANK35_L17N_FAN_SPEED6]

set_property PACKAGE_PIN N2 [get_ports DDR3_A0]
set_property PACKAGE_PIN K2 [get_ports DDR3_A1]
set_property PACKAGE_PIN M3 [get_ports DDR3_A2]
set_property PACKAGE_PIN K3 [get_ports DDR3_A3]
set_property PACKAGE_PIN M4 [get_ports DDR3_A4]
set_property PACKAGE_PIN L1 [get_ports DDR3_A5]
set_property PACKAGE_PIN L4 [get_ports DDR3_A6]
set_property PACKAGE_PIN K4 [get_ports DDR3_A7]
set_property PACKAGE_PIN K1 [get_ports DDR3_A8]
set_property PACKAGE_PIN J4 [get_ports DDR3_A9]
set_property PACKAGE_PIN F5 [get_ports DDR3_A10]
set_property PACKAGE_PIN G4 [get_ports DDR3_A11]
set_property PACKAGE_PIN E4 [get_ports DDR3_A12]
set_property PACKAGE_PIN D4 [get_ports DDR3_A13]
set_property PACKAGE_PIN F4 [get_ports DDR3_A14]
set_property PACKAGE_PIN L5 [get_ports DDR3_BA0]
set_property PACKAGE_PIN R4 [get_ports DDR3_BA1]
set_property PACKAGE_PIN J5 [get_ports DDR3_BA2]
set_property PACKAGE_PIN P5 [get_ports DDR3_CAS_N]
set_property PACKAGE_PIN P4 [get_ports DDR3_RAS_N]
set_property PACKAGE_PIN M5 [get_ports DDR3_WE_N]
set_property PACKAGE_PIN N1 [get_ports DDR3_CS_N]
set_property PACKAGE_PIN L2 [get_ports DDR3_CLK_P]
set_property PACKAGE_PIN M2 [get_ports DDR3_CLK_N]
set_property PACKAGE_PIN N2 [get_ports DDR3_CKE]
set_property PACKAGE_PIN N5 [get_ports DDR3_ODT]
set_property PACKAGE_PIN C3 [get_ports DDR3_DQ0]
set_property PACKAGE_PIN B3 [get_ports DDR3_DQ1]
set_property PACKAGE_PIN A2 [get_ports DDR3_DQ2]
set_property PACKAGE_PIN A4 [get_ports DDR3_DQ3]
set_property PACKAGE_PIN D3 [get_ports DDR3_DQ4]
set_property PACKAGE_PIN D1 [get_ports DDR3_DQ5]
set_property PACKAGE_PIN C1 [get_ports DDR3_DQ6]
set_property PACKAGE_PIN E1 [get_ports DDR3_DQ7]
set_property PACKAGE_PIN E2 [get_ports DDR3_DQ8]
set_property PACKAGE_PIN E3 [get_ports DDR3_DQ9]
set_property PACKAGE_PIN G3 [get_ports DDR3_DQ10]
set_property PACKAGE_PIN H3 [get_ports DDR3_DQ11]
set_property PACKAGE_PIN J3 [get_ports DDR3_DQ12]
set_property PACKAGE_PIN H2 [get_ports DDR3_DQ13]
set_property PACKAGE_PIN H1 [get_ports DDR3_DQ14]
set_property PACKAGE_PIN J1 [get_ports DDR3_DQ15]
set_property PACKAGE_PIN P1 [get_ports DDR3_DQ16]
set_property PACKAGE_PIN P3 [get_ports DDR3_DQ17]
set_property PACKAGE_PIN R3 [get_ports DDR3_DQ18]
set_property PACKAGE_PIN R1 [get_ports DDR3_DQ19]
set_property PACKAGE_PIN T4 [get_ports DDR3_DQ20]
set_property PACKAGE_PIN U4 [get_ports DDR3_DQ21]
set_property PACKAGE_PIN U2 [get_ports DDR3_DQ22]
set_property PACKAGE_PIN U3 [get_ports DDR3_DQ23]
set_property PACKAGE_PIN V1 [get_ports DDR3_DQ24]
set_property PACKAGE_PIN Y3 [get_ports DDR3_DQ25]
set_property PACKAGE_PIN W1 [get_ports DDR3_DQ26]
set_property PACKAGE_PIN Y4 [get_ports DDR3_DQ27]
set_property PACKAGE_PIN Y2 [get_ports DDR3_DQ28]
set_property PACKAGE_PIN W3 [get_ports DDR3_DQ29]
set_property PACKAGE_PIN V2 [get_ports DDR3_DQ30]
set_property PACKAGE_PIN V3 [get_ports DDR3_DQ31]
set_property PACKAGE_PIN C2 [get_ports DDR3_DQS0_P]
set_property PACKAGE_PIN B2 [get_ports DDR3_DQS0_N]
set_property PACKAGE_PIN G2 [get_ports DDR3_DQS1_P]
set_property PACKAGE_PIN F2 [get_ports DDR3_DQS1_N]
set_property PACKAGE_PIN R2 [get_ports DDR3_DQS2_P]
set_property PACKAGE_PIN T2 [get_ports DDR3_DQS2_N]
set_property PACKAGE_PIN W5 [get_ports DDR3_DQS3_P]
set_property PACKAGE_PIN W4 [get_ports DDR3_DQS3_N]
set_property PACKAGE_PIN A1 [get_ports DDR3_DM0]
set_property PACKAGE_PIN F1 [get_ports DDR3_DM1]
set_property PACKAGE_PIN T1 [get_ports DDR3_DM2]
set_property PACKAGE_PIN Y1 [get_ports DDR3_DM3]
set_property PACKAGE_PIN B4 [get_ports DDR3_RESET_N]
